--- 
title: "Notas de Aulas de Econometria"
author: "Marcos Minoru Hasegawa"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [economet.bib, book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Trata-se de notas de aulas da disciplina de Econometria do Curso de Economia do Departamento de Economia da Universidade Federal do Paraná."
---


```{r setup, include=FALSE}
library(formatR)
library(knitr)
library(ggplot2)
library(tinytex)
library(bibtex)
knitr::opts_chunk$set(
	echo = TRUE,
	error = FALSE,
	fig.height = 4,
	fig.width = 4,
	message = FALSE,
	warning = FALSE,
	cache = FALSE,
	tidy = TRUE,
	tidy.opts = list(width.cutoff = 50)
)
options(OutDec = ",")
```

# Licença {-}

Como está descrito no repositório, os poucos códigos originais desenvolvidos ao longo do texto estão sob a licença **GNU GPLv3** .

O texto e as artes gráficas elaboradas de forma original estão sob licença **Creative Commons BY-NC-SA 4.0**.

# Sobre o material {-}

A situação especial causada pela pandemia da COVID-19 forçou a muitos professores criarem materiais para facilitar aulas remotas das suas disciplinas. A disciplina SE308 Econometria da UFPR não poderia ser diferente. Então, o objetivo deste material é de suprir a falta das bibliografias básicas na sua versão digital com a disponibilização de forma digital e gratuita o que seria o material das notas das aulas da disciplina de Econometria. Não é o ideal, mas a ideia é melhorar o material com tempo.

# Sobre o Autor {-}

Professor do Departamento de Economia da Universidade Federal do Paraná. Engenheiro Agrônomo pela UNESP/Jaboticabal, Mestrado em Economia Agrária pela ESALQ/USP e Doutorado em Economia Aplicada pela ESALQ/USP, é um dos professores responsáveis pelas disciplinas de SE305 Estatística Econômica e Introdução à Econometria e SE308 Econometria ambas do curso de Economia da Universidade Federal do Paraná (UFPR). 
